server:
  port: 8081

jwt:
  secret: secret
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bankingapi
    password: FEPd@tc2dhA@btg$*6Uceqrfy
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  sql:
    init:
      mode: always
      continue-on-error: false


